<script setup lang="ts">
// panel/src/components/voice-report/VoiceReportView.vue
//
// Main container for the live voice-quality report view. Loads
// `VoiceReportData` via the prop API and renders the appropriate
// sub-views (per-probe, per-agent, per-workspace). The "Print /
// Save as PDF" button calls window.print() and the included print
// stylesheet produces a layout that matches
// `panel/template/voice-quality-report.html`.

import { computed, ref } from 'vue'
import VoiceReportHeader from './VoiceReportHeader.vue'
import VoiceReportSummary from './VoiceReportSummary.vue'
import VoiceReportDetails from './VoiceReportDetails.vue'
import VoiceReportPath from './VoiceReportPath.vue'
import VoiceReportMulti from './VoiceReportMulti.vue'
import VoiceReportWorkspace from './VoiceReportWorkspace.vue'
import type { VoiceReportData } from './types'

const props = defineProps<{
  data: VoiceReportData | null
  loading?: boolean
  error?: string | null
  /** Source label for the report subtitle (e.g. "agent-nyc-01" or workspace name). */
  sourceName?: string
}>()

const isPrinting = ref(false)

function handlePrint() {
  isPrinting.value = true
  // Allow the print dialog to take over; reset after a short delay so
  // the spinner shows while the dialog is open.
  setTimeout(() => window.print(), 50)
  setTimeout(() => {
    isPrinting.value = false
  }, 1500)
}

const viewMode = computed(() => props.data?.meta.view_mode ?? 'agent')

const hasTraceroute = computed(() => !!props.data?.traceroute?.hops?.length)
</script>

<template>
  <div class="vr-root">
    <div class="vr-toolbar no-print">
      <button :disabled="isPrinting || loading || !data" @click="handlePrint">
        <i class="bi bi-printer"></i>
        {{ isPrinting ? 'Opening print dialog…' : 'Print / Save as PDF' }}
      </button>
    </div>

    <div v-if="loading" class="vr-loading-state">
      <div class="spinner-border" role="status"></div>
      <p class="mt-3 text-muted">Loading voice quality data…</p>
    </div>

    <div v-else-if="error" class="alert alert-danger mx-auto mt-4" style="max-width: 600px">
      <i class="bi bi-exclamation-triangle"></i> {{ error }}
    </div>

    <template v-else-if="data">
      <!-- Per-probe or per-agent: single target view -->
      <template v-if="viewMode === 'probe' || viewMode === 'agent'">
        <div class="vr-page" id="page1">
          <VoiceReportHeader :meta="data.meta" />
          <VoiceReportSummary :data="data" />
          <footer class="vr-page-footer">
            <span>Generated by netwatcher.io — Voice / VoIP traffic simulation</span>
            <span>Page 1 of {{ hasTraceroute ? '3' : '2' }}</span>
          </footer>
        </div>

        <div class="vr-page" id="page2">
          <div class="vr-mini-header">
            <b>Voice Quality Report — Detailed Metrics</b>
            <span class="vr-mono">{{ data.meta.report_id }}</span>
          </div>
          <VoiceReportDetails :data="data" />
          <footer class="vr-page-footer">
            <span>Generated by netwatcher.io — Voice / VoIP traffic simulation</span>
            <span>Page 2 of {{ hasTraceroute ? '3' : '2' }}</span>
          </footer>
        </div>

        <div v-if="hasTraceroute" class="vr-page" id="page3">
          <div class="vr-mini-header">
            <b>Voice Quality Report — Path Analysis (MTR)</b>
            <span class="vr-mono">{{ data.meta.report_id }}</span>
          </div>
          <VoiceReportPath :data="data" />
          <footer class="vr-page-footer">
            <span>Generated by netwatcher.io — Voice / VoIP traffic simulation</span>
            <span>Page 3 of 3</span>
          </footer>
        </div>
      </template>

      <!-- Multi-pair (per-agent when there are multiple targets, or per-workspace) -->
      <VoiceReportMulti v-else-if="viewMode === 'multi'" :data="data" />

      <!-- Per-workspace: heatmap + rollup -->
      <VoiceReportWorkspace v-else-if="viewMode === 'workspace'" :data="data" />
    </template>
  </div>
</template>

<style scoped>
.vr-loading-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 60vh;
  color: #6b7280;
}
</style>